### ISSUE TITLE
Update docs to include the Absolute path on the server

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Xdebug#19]
We should should add this to the instructions:

![path](https://cloud.githubusercontent.com/assets/1377956/23454796/0172d386-fea0-11e6-8c53-91ac558f4be9.png)

**Comment by dashaluna** [comment]
@BronsonQuick Yes, I'm trying to push that... can you grand me the rights please?

**Comment by BronsonQuick** [comment]
Oops! I forgot to close this when @dashaluna did her PR! https://github.com/Chassis/Xdebug/pull/22
