### ISSUE TITLE
XDebug causes WordPress unit tests to be slow

### ISSUE THREAD

**Issue by fklein-lu** [Chassis/Xdebug#21]
I have been trying to figure out why WP Unit Tests run so slowly on my local setup. I think this is due to XDebug.

I started over with a fresh Chassis install, keeping all my previous extensions _except_ XDebug, and now everything runs fine.

Possibly related: [WordPress Trac #33580](https://core.trac.wordpress.org/ticket/33580).

**Comment by BronsonQuick** [comment]
@fklein-lu I just wanted circle back on this one again Fränk. Mike noted that `self::$ignore_files = $this->scan_user_uploads();` on the client site you two have been working on was slowing his tests down. Just wanted to confirm if that might've been the main issue you had too?

Also, Mike and I worked through this for a bit of a performance boost as well: https://github.com/Chassis/Chassis/commit/f7f42507990a4005072cc49b02d720fd5d4a2ba4 so make sure you pull down `master` to get a bit more of a performance boost as well!

**Comment by fklein-lu** [comment]
@BronsonQuick Indeed the fix that Mike deployed to the client project has sped up tests significantly.

Before the fix, this was running a single test:
`Time: 37.95 seconds, Memory: 44.00MB`

After the fix, running the whole suite with 52 tests:
`Time: 11.05 seconds, Memory: 42.00MB`

**Comment by BronsonQuick** [comment]
Awesome! Thanks @fklein-lu. I think I'll close this off for now.
