### ISSUE TITLE
Rename variable to avoid conflicts.

### ISSUE THREAD

**Issue by shadyvb** [Chassis/Xdebug#32]
https://github.com/Chassis/Xdebug/blob/e970b491f2cbc49b3b2e62b82195662bd0367fad/chassis.pp#L1

Xdebug should use another name for the variable as they cannot be reused by other extensions, ie: instead of `chassis_config` it should be `xdebug_config`.

**Comment by BronsonQuick** [comment]
Thank you Sir!
