### ISSUE TITLE
No support for PHP 7.2 

### ISSUE THREAD

**Issue by tareiking** [Chassis/Xdebug#36]
1. What operating system do you use?
Mac OSX 10.13.2
2. What version of Vagrant are you running?
1.9.6
3. Are you using VirtualBox or VMWare and which version are you using?
5.1.30r118389

**Problem** XDebug doesn't yet officially support PHP version 7.2 ([beta version has recently added support](https://xdebug.org/updates.php)). When installing this extension with PHP version 7.2 specified in a `config.yaml` file, it will install as normal on the next `vagrat provision`, but doesn't actually work. Leaving the developer sad and lonely when trying to use xdebug.

**Workaround** Can specify PHP version 7.1 or lower.

**PHP version with 7.0 showing xdebug support**
```
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.26-2+ubuntu16.04.1+deb.sury.org+2, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

**PHP version with 7.2 showing missing xdebug support**
```
PHP 7.2.0-2+ubuntu16.04.1+deb.sury.org+2 (cli) (built: Dec  7 2017 20:14:31) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0-2+ubuntu16.04.1+deb.sury.org+2, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by BronsonQuick** [comment]
Xdebug 2.6 has been shipped now so this is now fixed thanks to that:

```
PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  6 2018 16:11:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2-3+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

We can close this issue now!
