### ISSUE TITLE
Add ini settings for PHP CLI package as well

### ISSUE THREAD

**Issue by roborourke** [Chassis/Xdebug#37]
We're currently missing support for xdebug on CLI calls so debugging WP CLI commands is a pain.

The extension only adds the ini template for PHP-FPM, if we add it for CLI too it should work with the addition of exporting these env vars:

```
export PHP_IDE_CONFIG="serverName=<%= @hosts %>"
export XDEBUG_CONFIG="idekey=<%= @ide %>"
```

Props to @nprasath002

**Comment by BronsonQuick** [comment]
Fixed via: https://github.com/Chassis/Xdebug/pull/38 Thanks folks! 💖
