### ISSUE TITLE
Xdebug config isn't set for the CLI

### ISSUE THREAD

**Issue by johnbillion** [Chassis/Xdebug#46]
The `xdebug.ini` file generated by this extension is supposed to get copied into both `fpm/conf.d` and `cli/conf.d` ([ref](https://github.com/Chassis/Xdebug/blob/c95d8d3efd1462ae21e647416fc57f96f9e4322a/modules/xdebug/manifests/init.pp#L60-L77)), but the latter doesn't appear to happen. This means the Xdebug config in `xdebug.ini.erb` isn't available when using the CLI. Xdebug _is_ available on the CLI due to `cli/conf.d/20-xdebug.ini` being present, but all it does is load the extension with no config.

The result is that configuration for remote debugging etc isn't present on the CLI.

<img width="1021" alt="" src="https://user-images.githubusercontent.com/208434/38053577-6377ce04-32cc-11e8-9b42-1826d554c629.png">

Any idea what's up?

**Comment by BronsonQuick** [comment]
Good catch. Looking at the codebase it looks like we're missing `notify  => Service["php${php_version}-fpm"]` for `cli/conf.d`

**Comment by BronsonQuick** [comment]
If you run `vagrant ssh; sudo service php7.0-fpm restart` I think it should appear. I'll have some breakfast and fix this up!

**Comment by johnbillion** [comment]
The config as it stands doesn't actually work for the CLI because `xdebug.remote_connect_back` doesn't work on the CLI (due to there not being a remote IP address in `$_SERVER` in the CLI to connect back to).

We might need to use a different config for the CLI. Working on it at the mo.

**Comment by johnbillion** [comment]
I've got this working, just need to see if I can avoid having to manually put my remote IP address into `xdebug.remote_host`.

**Comment by BronsonQuick** [comment]
@johnbillion Can you double check you have the last version of this extension? https://github.com/Chassis/Xdebug/blob/master/modules/xdebug/templates/xdebug.ini.erb#L4 was added and should do the trick?

**Comment by johnbillion** [comment]
Ohhh yeah that looks like *exactly* what was needed.

**Comment by johnbillion** [comment]
I'll test and confirm.

**Comment by BronsonQuick** [comment]
P.S. Auto updates are coming soon: https://github.com/Chassis/Chassis/pull/504

**Comment by johnbillion** [comment]
The new config works like a treat on the CLI and via FPM!

The config file also correctly gets moved into place (even after I manually delete it) so I guess my version of `chassis/xdebug` was several months old.

All good!

**Comment by johnbillion** [comment]
#38 is what I needed
