### ISSUE TITLE
502 Bad Gateway with PHP 7.3

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Xdebug#49]
If you change your Chassis configuration to PHP 7.3 and visit http://vagrant.local you will received a 502 Bad Gateway message.

**Comment by johnbillion** [comment]
Ah-ha, there isn't yet a stable version of Xdebug that supports PHP 7.3. https://xdebug.org/updates.php

**Comment by BronsonQuick** [comment]
@johnbillion Sorry for the delay on this! I think you should be all good now with my latest change. It'll install Xdebug v2.7.0rc1 with PHP 7.3. Let me know if you have any issues!

**Comment by johnbillion** [comment]
Cool! Thanks Bronson.
