### ISSUE TITLE
xdebug install on MacOSX Catalina 10.15.2

### ISSUE THREAD

**Issue by robshpiel1** [Chassis/Xdebug#62]
Having major difficulty installing xdebug for mac due to upgrades in OS and I assume Apple SIC.  I followed instructions to compile and the only way I was able to get it compiled was via:
[(https://profilingviewer.com/installing-xdebug-on-catalina.html)]

Using instructions on xdebug website gives many errors finding php.h as well as trying to write to directories I can no longer write to.

pecl install does not work is either (after completely wiping homebrew and reinstalling homebrew, php, apache, etc).

Now I receive the following error on apache log:
```
Failed loading /usr/local/php/extensions/xdebug.so:  dlopen(/usr/local/php/extensions/xdebug.so, 9): Symbol not found: _zend_post_startup_cb
  Referenced from: /usr/local/php/extensions/xdebug.so
  Expected in: flat namespace
 in /usr/local/php/extensions/xdebug.so
```

I feel so close to having this work with PHP Version 7.2.26 and Apache/2.4.41 (Unix) but still nothing yet.  

1. What operating system do you use?
Mac OSX Catalina 10.15.2

2. What version of Vagrant are you running?
NA

3. Are you using VirtualBox or VMWare and which version are you using?
NO

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
No

5. Do you have any Chassis other extensions installed? If so, what are they?
No

**Comment by BronsonQuick** [comment]
Hey @robshpiel1, thanks for opening an issue in regards to Xdebug. This repository is actually for a Chassis extension that uses Xdebug. I think you're looking for the official Xdebug bug tracking software which is [here](https://bugs.xdebug.org/my_view_page.php). I think if you open an issue there you should get some help on your issue.

I'm closing this issue as it isn't an issue with our extension.
